spring:
  jpa:
    hibernate:
      ddl-auto: create # test
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    base-package: com.ssu.commerce.book
    title: book api
    version: 1.0

logging:
  level:
    p6spy: info

server:
  port: 8081
grpc:
  client:
    test:
      address: 'static://127.0.0.1:9090'
      negotiationtype: plaintext
