grpc:
  server:
    port: 0

spring:
  jpa:
    hibernate:
      connection:
        charSet: UTF-8
        characterEncoding: utf8
        useUnicode: true
      ddl-auto: create # test
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:tc:mysql:///
    username:
    password:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    hikari:
      maximum-pool-size: 5
  redis:
    host: localhost
    port: 6379

springdoc:
  swagger-ui:
    base-package: com.ssu.commerce.book
    title: book api
    version: 1.0

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG # Hibernate SQL 로그를 DEBUG 레벨로 설정
      com:
        p6spy: DEBUG # p6spy 로그를 DEBUG 레벨로 설정하여 SQL 로그를 더욱 상세하게 추적
